version: '3.4'

services:
  app:
    build: ./server
    command: npm run dev
    ports:
      - "3001:3001"
    volumes: 
      - ./server/src:/app

  
  vue-app:
    build: ./client
    command: npm run serve
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/vue-app
  